on: [push]

name: CI

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Cache Packages
        uses: Swatinem/rust-cache@v1

      - name: Build
        run: cargo build --release

      - uses: actions/upload-artifact@v2
        name: Upload a Build Artifact
        with:
          name: image-host
          path: target/release/image-host
